openapi: 3.0.0
info:
  title: Claude Code OpenAI Wrapper API
  description: OpenAI-compatible API wrapper for Claude Code with session management and tool support
  version: 1.0.0
  contact:
    name: API Support
    url: https://github.com/jorge123255/claude-code-openai-wrapper
servers:
  - url: http://localhost:8000
    description: Local development server
  - url: http://192.168.1.11:8000
    description: Docker container (example)
paths:
  /health:
    get:
      summary: Health check
      description: Check if the API server is running
      tags:
        - System
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: claude-code-openai-wrapper
  
  /v1/models:
    get:
      summary: List available models
      description: Get a list of all available Claude models
      tags:
        - Models
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: List of models
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    example: list
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: claude-3-5-sonnet-20241022
                        object:
                          type: string
                          example: model
                        owned_by:
                          type: string
                          example: anthropic
  
  /v1/chat/completions:
    post:
      summary: Create chat completion
      description: Create a chat completion with Claude (OpenAI-compatible)
      tags:
        - Chat
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                  description: Model ID to use
                  enum:
                    - claude-sonnet-4-20250514
                    - claude-opus-4-20250514
                    - claude-3-7-sonnet-20250219
                    - claude-3-5-sonnet-20241022
                    - claude-3-5-haiku-20241022
                  example: claude-3-5-sonnet-20241022
                messages:
                  type: array
                  description: Array of messages
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum: [system, user, assistant]
                      content:
                        type: string
                      name:
                        type: string
                        nullable: true
                temperature:
                  type: number
                  minimum: 0
                  maximum: 2
                  default: 1.0
                top_p:
                  type: number
                  minimum: 0
                  maximum: 1
                  default: 1.0
                n:
                  type: integer
                  default: 1
                  maximum: 1
                  description: Only n=1 is supported
                stream:
                  type: boolean
                  default: false
                stop:
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                max_tokens:
                  type: integer
                  nullable: true
                  description: Not supported by Claude Code
                presence_penalty:
                  type: number
                  minimum: -2
                  maximum: 2
                  default: 0
                frequency_penalty:
                  type: number
                  minimum: -2
                  maximum: 2
                  default: 0
                logit_bias:
                  type: object
                  description: Not supported by Claude Code
                user:
                  type: string
                session_id:
                  type: string
                  description: Optional session ID for conversation continuity
                enable_tools:
                  type: boolean
                  default: false
                  description: Enable Claude Code tools (Read, Write, Bash, etc.)
      responses:
        '200':
          description: Successful completion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletion'
            text/event-stream:
              schema:
                type: string
                description: Server-sent events for streaming
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/auth/status:
    get:
      summary: Check authentication status
      description: Get information about Claude Code authentication
      tags:
        - Authentication
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Authentication status
          content:
            application/json:
              schema:
                type: object
                properties:
                  claude_code_auth:
                    type: object
                    properties:
                      method:
                        type: string
                        enum: [browser, api_key, bedrock, vertex, claude_cli]
                      status:
                        type: object
                      environment_variables:
                        type: array
                        items:
                          type: string
                  server_info:
                    type: object
                    properties:
                      api_key_required:
                        type: boolean
                      api_key_source:
                        type: string
                      version:
                        type: string
  
  /v1/sessions:
    get:
      summary: List active sessions
      description: Get a list of all active chat sessions
      tags:
        - Sessions
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: List of sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/SessionInfo'
                  count:
                    type: integer
  
  /v1/sessions/{session_id}:
    get:
      summary: Get session details
      description: Get detailed information about a specific session
      tags:
        - Sessions
      security:
        - ApiKeyAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                  conversation:
                    type: object
                    properties:
                      messages:
                        type: array
                        items:
                          type: object
                  metadata:
                    $ref: '#/components/schemas/SessionInfo'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete session
      description: Delete a specific session and its history
      tags:
        - Sessions
      security:
        - ApiKeyAuth: []
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Session deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  session_id:
                    type: string
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/sessions/stats:
    get:
      summary: Get session statistics
      description: Get statistics about all active sessions
      tags:
        - Sessions
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Session statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  active_sessions:
                    type: integer
                  total_messages:
                    type: integer
                  memory_usage_mb:
                    type: number
                  oldest_session:
                    type: string
                    format: date-time
                  newest_session:
                    type: string
                    format: date-time

components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      description: Optional API key protection (if enabled)
  
  schemas:
    ChatCompletion:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
          example: chat.completion
        created:
          type: integer
        model:
          type: string
        choices:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
              message:
                type: object
                properties:
                  role:
                    type: string
                  content:
                    type: string
                  name:
                    type: string
                    nullable: true
              finish_reason:
                type: string
        usage:
          type: object
          properties:
            prompt_tokens:
              type: integer
            completion_tokens:
              type: integer
            total_tokens:
              type: integer
        system_fingerprint:
          type: string
          nullable: true
    
    SessionInfo:
      type: object
      properties:
        session_id:
          type: string
        created_at:
          type: string
          format: date-time
        last_active:
          type: string
          format: date-time
        message_count:
          type: integer
        expires_at:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
            type:
              type: string
            code:
              type: string
              nullable: true

security:
  - ApiKeyAuth: []

tags:
  - name: System
    description: System endpoints
  - name: Models
    description: Model management
  - name: Chat
    description: Chat completion endpoints
  - name: Authentication
    description: Authentication status
  - name: Sessions
    description: Session management